
// Objective-C API for talking to the following Go packages
//
//	gamecenter.mobi/paicode/sdk/gamesdklib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gamesdklib_FRAMEWORK_H__
#define __Gamesdklib_FRAMEWORK_H__

#include "Gamesdklib.objc.h"
#include "universe.objc.h"

#endif
